spring.application.name=springsieutoc

spring.profiles.active=prod

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/fakedata
spring.datasource.username=api11
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#config jwt
hoidanit.jwt.base64-secret=3Ne3BvvPBlhFa7Yi7btimnoOeO0FOXHdHEjizv/gm3Y=

#1day
hoidanit.jwt.access-token-validity-in-seconds=86400000

hoidanit.jwt.refresh-token-validity-in-seconds=86400000

tim.of.cookie=86400000

# default page size
spring.data.web.pageable.default-page-size=10

# max page size
spring.data.web.pageable.max-page-size=100

#false: start with 0; true: start with 1
spring.data.web.pageable.one-indexed-parameters=true

